project_name: z21scan
version: 2

release:
  github:
    owner: trains-io
    name: z21scan
  name_template: "Release {{.Version}}"
  draft: true
  prerelease: auto

changelog:
  disable: true

builds:
  - env:
      - CGO_ENABLED=0

archives:
  - name_template: "z21scan-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    formats:
      - zip

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

nfpms:
  - file_name_template: "z21scan-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    bindir: /usr/local/bin
    formats:
      - deb
      - rpm
